### ISSUE TITLE
RFE: allow specifying a different config file path

### ISSUE THREAD

**Issue by kcgthb** [CLIP-HPC/SlurmCommander#3]
Hi!

I'd like to suggest the possibility to specify a different path for the configuration file, ideally set via an environment variable.

Site administrators may choose to make this tool available to their users via an environment module, and provide a default configuration file that would better be located alongside the software (in a NFS-shared installation directory, for instance), rather than having to distribute it to `/etc` on every single node in the cluster.

Something like `SCOM_CONF` that the program could check in addition to `/etc/scom/scom.conf` and `$HOME/scom/scom.conf`.

Also, in the interest of compatibility,`$XDG_CONFIG_HOME` could probably be used instead of a hard-coded `$HOME/scom/scom.conf` (see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

----
Great work, by the way, this tool has a huge potential to make things easier for users! :tada:

**Comment by pja237** [comment]
Signing everything you've said. 100% agree.
I'll start the work on this as soon as the #1 is cleared out of the way.

**Comment by pja237** [comment]
Sorry, forgot to comment....
So, i didn't remove the old ones, they're doing no harm being left in (/etc/scom and $HOME/scom), for now...
Added SCOM_CONF var support and the $XDG_CONFIG_HOME/scom/scom.conf or $HOME/.config/scom.conf in case the former is unset/empty.

**Comment by kcgthb** [comment]
Nice, thanks!

**Comment by pja237** [comment]
You're most welcome, a real goldmine of feedback :1st_place_medal: 
Keep the ideas coming and we'll try to clear them as fast as we can.
