### ISSUE TITLE
RFE: allow filtering per partition in Cluster tab

### ISSUE THREAD

**Issue by kcgthb** [CLIP-HPC/SlurmCommander#8]
A useful addition to the "Cluster" view would be the possibility to filter by partition.

**Comment by pja237** [comment]
Ok, that's a "tricky" one.
The way filtering is done is by concatenating strings from selected columns and then running one regexp across this big string. That way we get away with some nice gimmicks using very little code, like: ability to write multi-column filters like `jobname_re.*username_re.*(PEND|RUN)`

The challenge with partitions filtering, at least on our site, and that's the reason they're not included in the filter string is that we have single letter partition names (c,g,m), which doesn't work that well with the logic above (but we do have partition letter in the node naming schema, e.g. clip-[gmc], so we get away with partition filtering) :laughing: 
I'll have to think a bit about how to tackle this, any ideas/proposals how to solve the partition filtering to the user in this situation?

**Comment by pja237** [comment]
Done. Single letter partitions can be filtered out with the following form: `\.m\.`.
